#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
   { binding = "KV", id = "你的KV命名空间ID" }
]

[assets]
directory = "./public"
